sonar.projectKey=when-drones-go-blind
sonar.projectName=When Drones Go Blind
sonar.projectVersion=1.0
sonar.sources=ros_ws/px4_ros_ws/src/swarm_discovery/swarm_discovery
sonar.language=py
sonar.python.version=3.10
sonar.token=squ_3072c5f0c94db647bbd89204a7d64b642a34dfe5
